<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
	<title>Login</title>
	<link rel="stylesheet" type="text/css" href="ClassesPadroes/style.css">
  <script src="ClassesPadroes/jquery-3.2.1.js"></script>
  <script type="text/javascript" src="ClassesPadroes/javinha.js"></script>

</head>
  

 <body>


  <div id="menu">
        <div><center><label class="nomeLogo">DESBRAVA</label></center></div>
        <div class="mudar" id="ex"><center><label class="fontMen">Exercícios</label></center></div>
        <div class="mudar" id="pro"><center><label class="fontMen">Provas</label></center></div>
        <div class="mudar" id="ami"><center><label class="fontMen">Amigos</label></center></div>
        <div id="desaparecer"><img src="Imagens/login.png"  class="login"></div>
  </div>
  <div class="aparecer"><div id="log">Logar</div><div id="deslog">Deslogar</div></div>


  

